### ISSUE TITLE
滑块验证码返回坐标问题

### ISSUE THREAD

**Issue by yuzaii** [sml2h3/ddddocr#109]
请问滑块返回的{'target_y': 0, 'target': [400, 0, 510, 360]}具体是什么坐标呀？

**Comment by yuzaii** [comment]
我明白了哈哈哈谢谢大佬

**Comment by OwnerCM** [comment]
> 我明白了哈哈哈谢谢大佬

请问这几个坐标分别代表什么？小白还没搞明白
