### ISSUE TITLE
请问我将程序封装后运行，每次都报这种错误是什么原因啊？

### ISSUE THREAD

**Issue by xue-11** [sml2h3/ddddocr#11]
[ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from C:\Users\ADMINI~1\AppData\Local

\Temp\2\_MEI30202\ddddocr\common.onnx failed:Load model C:\Users\ADMINI~1\AppData\Local

\Temp\2\_MEI30202\ddddocr\common.onnx failed. File doesn't exist

麻烦帮忙看下，十分感谢。

**Comment by YYYet** [comment]
打包spec datas=[('本地ddddocr路径','ddddocr')]
左边是你要添加的filename（相对路径即可），右边是拷贝到项目中之后的文件夹名字
