### ISSUE TITLE
滑块拼图，存在两个相同缺口坑位的拼图，有解决方法吗？

### ISSUE THREAD

**Issue by LEIRONGHUA** [sml2h3/ddddocr#110]
![image](https://user-images.githubusercontent.com/4002277/224950589-173e07f6-d62f-401c-afe1-3d166fade84a.png)
类似上图，已知slider滑动图片的top偏移量，能否改进识别呢？
背景图：
![image](https://user-images.githubusercontent.com/4002277/224956279-93d989bc-17f7-44f9-85dd-703d5b82dafb.png)
滑块图：
![image](https://user-images.githubusercontent.com/4002277/224956376-d3336852-fbdf-4ca0-ab59-f044546f9077.png)

**Comment by Yaaasuo** [comment]
自己慢慢折腾去吧，这tm谁能帮得了你

**Comment by LEIRONGHUA** [comment]
> 自己慢慢折腾去吧，这tm谁能帮得了你

嗯，已经折腾，解决了。 现在关闭这个问题。

**Comment by Amadeus331** [comment]
> > 自己慢慢折腾去吧，这tm谁能帮得了你
> 
> 嗯，已经折腾，解决了。 现在关闭这个问题。

可以分享下解决方案吗😊

**Comment by SweetInk** [comment]
> > > 自己慢慢折腾去吧，这tm谁能帮得了你
> > 
> > 
> > 嗯，已经折腾，解决了。 现在关闭这个问题。
> 
> 可以分享下解决方案吗😊

估计基于top偏移，剪裁top以上区域，再识别

**Comment by Amadeus331** [comment]
> > > > 自己慢慢折腾去吧，这tm谁能帮得了你
> > > 
> > > 
> > > 嗯，已经折腾，解决了。 现在关闭这个问题。
> > 
> > 
> > 可以分享下解决方案吗😊
> 
> 估计基于top偏移，剪裁top以上区域，再识别

### 这个思路挺好，我尝试实现了一下，不知道有没有更合适的方法

```
def get_slide_distance(target_img_bytes: bytes = None, background_img_bytes: bytes = None):
    # 获取滑块图片高度
    target = det.get_target(target_img_bytes)

    # 对滑块和背景图片进行裁剪
    target_img = Image.open(BytesIO(target_img_bytes))
    background_img = Image.open(BytesIO(background_img_bytes))
    target_box = (0, target[2], target_img.width, target_img.height)
    target_img = target_img.crop(target_box)
    background_box = (0, target[2], background_img.width,background_img.height)
    background_img = background_img.crop(background_box)

    # 将图片转换为bytes类型
    with BytesIO() as target_buffer:
        target_img.save(target_buffer, format='PNG')
        target_bytes = target_buffer.getvalue()
    with BytesIO() as background_buffer:
        background_img.save(background_buffer, format='PNG')
        background_bytes = background_buffer.getvalue()

    # 返回滑动距离
    return det.slide_match(target_bytes, background_bytes)
```
