### ISSUE TITLE
ocr能不能给提示文字啊

### ISSUE THREAD

**Issue by Martinits** [sml2h3/ddddocr#114]
我试了http://146.56.204.113:19199/preview?project_name=netease_zh 的ocr，就是ddddocr包里边打广告那个，可以给提示文字，感觉比这个准多了，想问下这个能不能给提示文字啊

**Comment by iamxiaojianzheng** [comment]
> 我试了http://146.56.204.113:19199/preview?project_name=netease_zh 的ocr，就是ddddocr包里边打广告那个，可以给提示文字，感觉比这个准多了，想问下这个能不能给提示文字啊

请问这个接口怎么使用？能给个文档链接吗？

**Comment by Martinits** [comment]
不能用，这帮人借着开源搞臭钱的，快跑吧
