### ISSUE TITLE
请问我用pyinstaller修改了spec把common.onnx包含在data后-F封装，exe还是闪退是什么情况呢

### ISSUE THREAD

**Issue by Janzyz3** [sml2h3/ddddocr#12]
之前是显示 no such file：common.onnx，后来我修改了spec，把common.onnx加入了，可以在我自己的电脑执行exe。
但是到没有安装python的电脑环境下，就出现闪退了。（我的py代码中有selenium的部分，我还特意把webdriver.exe和生成的exe放到了同一目录，依旧闪退）

**Comment by sml2h3** [comment]
pyinstaller我也没怎么用过，我个人认为还是路径问题，可以考虑 #11 。另外也可以改成通过os获取common.onnx的绝对路径，然后ddddocr代码中加载onnx模型的地方改为绝对路径

**Comment by sml2h3** [comment]
pyinstaller我也没怎么用过，我个人认为还是路径问题，可以考虑 #11 。另外也可以改成通过os获取common.onnx的绝对路径，然后ddddocr代码中加载onnx模型的地方改为绝对路径

> 之前是显示 no such file：common.onnx，后来我修改了spec，把common.onnx加入了，可以在我自己的电脑执行exe。
> 但是到没有安装python的电脑环境下，就出现闪退了。（我的py代码中有selenium的部分，我还特意把webdriver.exe和生成的exe放到了同一目录，依旧闪退）
