### ISSUE TITLE
抖音文字点选验证的加粗之后的文字 ocr 和 检测 都不行

### ISSUE THREAD

**Issue by 332123342** [sml2h3/ddddocr#121]
![big_2_bak](https://github.com/sml2h3/ddddocr/assets/120700204/240f13b6-92ad-47f5-bed1-0d22f6218041)

**Comment by LeanFly** [comment]
抖音的文字点选目前识别确实不稳定。我试了几个库都一般。

**Comment by LeanFly** [comment]
估计还是得自定义一波

**Comment by 332123342** [comment]
![chat](https://github.com/sml2h3/ddddocr/assets/120700204/1cf02e76-99f8-4d6c-8acf-3f17c78ad87a)
这种正常的文字里@也识别的有问题
