### ISSUE TITLE
Pillow版本更新

### ISSUE THREAD

**Issue by Do1e** [sml2h3/ddddocr#128]
使用最新的Pillow 10.0.0报错：
```
".../ddddocr/__init__.py", line 1614, in classification
    image = image.resize((int(image.size[0] * (64 / image.size[1])), 64), Image.ANTIALIAS).convert('L')
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```
应该为`Image.LANCZOS`，或修改install_requires
[参考Pillow文档](https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#constants)

**Comment by QAQQL** [comment]
pip install Pillow==9.2.0

**Comment by marlkiller** [comment]
> 

pip3 install --force-reinstall -v "Pillow==9.5.0"
