### ISSUE TITLE
异常报错

### ISSUE THREAD

**Issue by w55565** [sml2h3/ddddocr#13]
![image](https://user-images.githubusercontent.com/49785956/134337324-053da2f6-063a-412c-9646-a56cc85bf7bb.png)
这是个啥情况呢

**Comment by sml2h3** [comment]
目测是系统环境问题

> ![image](https://user-images.githubusercontent.com/49785956/134337324-053da2f6-063a-412c-9646-a56cc85bf7bb.png)
> 这是个啥情况呢

**Comment by 3215656174** [comment]
onnxruntime 为什么 下载不了
