### ISSUE TITLE
ddddocr与10.0.0以上的pillow不兼容

### ISSUE THREAD

**Issue by MarvinTerry** [sml2h3/ddddocr#134]
运行时会报出如下错误
```
image = image.resize((int(image.size[0] * (64 / image.size[1])), 64), Image.ANTIALIAS).convert('L')
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```
原因是```ANTIALIAS```在新版的pillow中被去除了，希望作者能够使用别的标签替换，下面是网络上的一个范例。
https://stackoverflow.com/questions/76616042/attributeerror-module-pil-image-has-no-attribute-antialias

**Comment by hsyysy** [comment]
#126
