### ISSUE TITLE
能不能直接输入base64码🌝

### ISSUE THREAD

**Issue by bukaixyz** [sml2h3/ddddocr#146]
有个网站 验证码图片是以base64码的形式返回的 能不能直接输入base64码到ddddocr库里面，省着转换来转换去 麻烦的要死🌝

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by coolxitech** [comment]
base64.b64decode(image_base64)
