### ISSUE TITLE
partially initialized module 'ddddocr' has no attribute 'DdddOcr' (most likely due to a circular import)

### ISSUE THREAD

**Issue by FearlessPeople** [sml2h3/ddddocr#147]
【环境】
Python 3.8.10 
ddddocr 1.4.8

【问题】
安装完ddddocr后，运行示例报错partially initialized module 'ddddocr' has no attribute 'DdddOcr'
安装的版本是：1.4.8
```
pip list | grep ddddocr
ddddocr                1.4.8
```
![image](https://github.com/sml2h3/ddddocr/assets/12705866/fd91201d-e342-491a-9537-cbb51dc9b8be)
![image](https://github.com/sml2h3/ddddocr/assets/12705866/1837d4bd-b03c-4acf-a6dc-690071762365)

**Comment by sml2h3** [comment]
你自己本身的文件的名称不要叫ddddocr.py，改一个，比如说aaa.py
