### ISSUE TITLE
opencv-python最新版不适配，需要降级

### ISSUE THREAD

**Issue by overXsky** [sml2h3/ddddocr#148]
环境：macos 14.1  python3.10
问题描述：pip install ddddocr
执行下述语句
import ddddocr
ocr = ddddocr.DdddOcr()
报错：AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)

解决方案：
pip install opencv-python==3.4.16.59
成功，没有测试过其他版本，建议在requirements.txt中加上版本号

**Comment by sml2h3** [comment]
收到，修复fixed!
