### ISSUE TITLE
目标检测只能返回坐标，可以返回识别出的对象的内容嘛

### ISSUE THREAD

**Issue by cyqresig** [sml2h3/ddddocr#156]
![网易点选汉字](https://github.com/sml2h3/ddddocr/assets/1388338/124c52b0-f0f9-4422-b053-84c1207eb872)

如上图，请问现在最新的 1.4.0 版本，看文档介绍，目标检测只能返回坐标，
有没有办法将识别出的对象的内容也返回出来？（比如文字或图形符号）

# poses = det.detection(image)
# print(poses)
# [[0, 345, 30, 376], [28, 346, 59, 378], [57, 345, 88, 375], [2, 181, 67, 250], [121, 163, 188, 229], [223, 119, 291, 187]]
以上为尝试 API 的返回结果，目前识别成功后，只能返回坐标

**Comment by alair074** [comment]
+1

**Comment by chengxiang123aa** [comment]
您好，请问有解决方案吗?

**Comment by zixing131** [comment]
先识别出对象，再切图进行文字识别

**Comment by chengxiang123aa** [comment]
> 先识别出对象，再切图进行文字识别

你好，我尝试过，我觉得ddddocr的目标检测做的很好，位置信息识别很准，但是识别的文字效果太差，根据位置信息切分出来的图片基本不能识别正确。不知道你有没有什么比较好的解决方案，还是说得自己去训练推理模型呢。

**Comment by zixing131** [comment]
> > 先识别出对象，再切图进行文字识别
> 
> 你好，我尝试过，我觉得ddddocr的目标检测做的很好，位置信息识别很准，但是识别的文字效果太差，根据位置信息切分出来的图片基本不能识别正确。不知道你有没有什么比较好的解决方案，还是说得自己去训练推理模型呢。

你这个文字被旋转变形了，可以自己预处理一下文字然后自己训练或者尝试直接对比文字图像，用图像对比的算法
