### ISSUE TITLE
用pyinstaller封装之后再执行会报错

### ISSUE THREAD

**Issue by Edmond-Lee-Zse-Wong** [sml2h3/ddddocr#160]
- 系统环境：win10
- 问题相关组件版本：
python：3.7.6 
pyinstaller：4.5    
ddddocr：1.4.10
- 运行指令：
在vscode执行以下命令一切正常，之后用pyinstaller封装为exe，再执行就报错
```
import ddddocr

ocr = ddddocr.DdddOcr()
with open("veriCode2.png", 'rb') as f:
        image = f.read()
res = ocr.classification(image)
print(res)
```

- 报错代码：
```
2023-12-31 17:08:34.4607321 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1671 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    ocr = ddddocr.DdddOcr()
  File "ddddocr\__init__.py", line 1461, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 360, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 397, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from C:\Users\18191\AppData\Local\Temp\_MEI294722\ddddocr\common_old.onnx failed:Load model C:\Users\18191\AppData\Local\Temp\_MEI294722\ddddocr\common_old.onnx failed. File doesn't exist
```
我检查了“C:\Users\18191\AppData\Local\Temp\_MEI294722\ddddocr\common_old.onnx”，该路径下确实没有这个文件。请教下各位大佬这个问题应该怎样解决，我非常需要将代码封装再执行，谢谢各位

**Comment by Edmond-Lee-Zse-Wong** [comment]
上述问题已解决
1. 正常打包
`pyinstaller -F xx.py`
2. 修改当前目录下的xx.spec文件
 记事本打开xx.spec，并将`datas=[]`改为`datas=[('./common_old.onnx','ddddocr')]`
3. 用listary或其他文件搜索软件找到common_old.onnx并将其复制到当前文件目录下
4. 执行以下代码
`pyinstaller .\xx.spec`

上述操作之后再执行exe即可正常运行

参考链接：
[https://zhuanlan.zhihu.com/p/645021419](url)

**Comment by Edmond-Lee-Zse-Wong** [comment]
上述问题已解决
1. 正常打包
`pyinstaller -F xx.py`
2. 修改当前目录下的xx.spec文件
 记事本打开xx.spec，并将`datas=[]`改为`datas=[('./common_old.onnx','ddddocr')]`
3. 用listary或其他文件搜索软件找到common_old.onnx并将其复制到当前文件目录下
4. 执行以下代码
`pyinstaller .\xx.spec`

上述操作之后再执行exe即可正常运行

参考链接：
[https://zhuanlan.zhihu.com/p/645021419](url)

**Comment by lqdahv** [comment]
感谢大佬 终于好了
