### ISSUE TITLE
计算两张缺口滑动图时，报错(-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

### ISSUE THREAD

**Issue by yuzepeng** [sml2h3/ddddocr#163]
如题，使用det.slide_match(target_bytes, background_bytes)函数时 正确的传入了两张图片的byte数据，结果直接报一下错误

`target = cv2.cvtColor(np.asarray(target), cv2.IMREAD_ANYCOLOR)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'`

使用的图片是 京东 登录时拼图验证图片

如果在slide_match函数调用时加上simple_target=True 不会报错 但是效果就不行了

**Comment by Lockey-J** [comment]
因为get_target函数有点问题。无法准确截取滑块导致。修改一下这个函数就可以了。

**Comment by zehuiguan** [comment]
> 因为get_target函数有点问题。无法准确截取滑块导致。修改一下这个函数就可以了。

请问这个怎么改呢

**Comment by Lockey-J** [comment]
使用opencv的轮廓。获取最大轮廓就行了。或者原函数增加2个y方向的缓存变量进行递进查找。

**Comment by JustForSmiling** [comment]
你好，请问滑块的小块图片怎么单独获取到的呀，一般情况下，小块不也是在大图上面吗？

**Comment by 86maid** [comment]
def get_target(self, img_bytes: bytes = None):
    image = Image.open(io.BytesIO(img_bytes))
    width, height = image.size
    start_x = width
    start_y = height
    end_x = 0
    end_y = 0

    for x in range(width):
        for y in range(height):
            p = image.getpixel((x, y))
            if p[3] != 0:  # Check alpha channel for transparency
                if x < start_x:
                    start_x = x
                if y < start_y:
                    start_y = y
                if x > end_x:
                    end_x = x
                if y > end_y:
                    end_y = y

    if start_x > end_x or start_y > end_y:
        # No non-transparent pixels found
        return image.crop((0, 0, width, height)), 0, 0
    else:
        cropped_image = image.crop((start_x, start_y, end_x + 1, end_y + 1))
        return cropped_image, start_x, start_y
