### ISSUE TITLE
这个最大支持多大的图片啊，截图生成的图片，太大了识别不了吗

### ISSUE THREAD

**Issue by chenshi1993** [sml2h3/ddddocr#170]
这个最大支持多大的图片啊，截图生成的图片，太大了识别不了吗，截图有500kb，超限制了吗

**Comment by sml2h3** [comment]
本地识别的，没有限制的，目前仅能单行识别，所以尽量图片的主题内容位要是别的字符，参考常见的验证码图片，所以截图的话建议精准一些到验证码图片的区域而不是全屏哈~
