### ISSUE TITLE
window 环境 安装之后报错 

### ISSUE THREAD

**Issue by MissAlang** [sml2h3/ddddocr#173]
from .onnxruntime_pybind11_state import *  # noqa
ImportError: DLL load failed while importing onnxruntime_pybind11_state: 找不到指定的程序。

**Comment by lor2012** [comment]
win7不支持1.14.1版本以上，
pip install onnxruntime==1.14.1
后再试一下，问题应该可以解决

**Comment by sml2h3** [comment]
1、确认自己安装的python是64位
2、安装[vc运行库](https://www.ghxi.com/yxkhj.html)
