### ISSUE TITLE
如何限制输出字符的数量？

### ISSUE THREAD

**Issue by Anonymous-so** [sml2h3/ddddocr#183]
如下图，验证码均为5位字符的数字或字母。目前已知可以通过set_range控制输出为字母或数字，但是无法控制模型输出的字符数为5个。请问是否有什么方法可以达成此目标呢？
![图片](https://github.com/sml2h3/ddddocr/assets/31177702/2ed32d74-d286-4010-b3cb-93bc678a9b55)

**Comment by sml2h3** [comment]
可以考虑设置概率阈值，比如90%可能性的才要，或者只取前若干准确率的字符
