### ISSUE TITLE
每次运行都遇到这样的错误提示

### ISSUE THREAD

**Issue by chengriyue** [sml2h3/ddddocr#185]
[W : onnxruntime :  execution_frame.cc : 858 onnxruntime :: ExecutionFrame :: VerifyOutputSizes] Expected shape from model of {1,-1} does not match actual shape of {19,1,8210} for output 387

**Comment by yiyuhewei** [comment]
我也遇到了，我用的py310的没有这个问题，换到py312自动下了个ddddocr1.5.3版本的就出现这个问题了，实际运行倒是没出错，只是控制台一直输出，有点难看

**Comment by chengriyue** [comment]
我后来在ddddocr代码中加入了  onnxruntime.set_default_logger_severity(3)这行代码，屏蔽了警告。就啥都没了




***@***.***
 
发件人： yiyuhewei
发送时间： 2024-05-14 15:47
收件人： sml2h3/ddddocr
抄送： chengriyue; Author
主题： Re: [sml2h3/ddddocr] 每次运行都遇到这样的错误提示 (Issue #185)
我也遇到了，我用的py310的没有这个问题，换到py312自动下了个ddddocr1.5.3版本的就出现这个问题了，实际运行倒是没出错，只是控制台一直输出，有点难看

**Comment by sml2h3** [comment]
已修复1.5.4

**Comment by TuDouqwq** [comment]
> 已修复1.5.4

可以问一下是怎么解决的吗。我现在用的node.js版本也出这个警告，但是运行结果是没问题的
