### ISSUE TITLE
这个如何识别算式型验证码

### ISSUE THREAD

**Issue by metoto** [sml2h3/ddddocr#19]
试了几张图，无法识别符号，只能识别出数字
![4](https://user-images.githubusercontent.com/5674572/143798574-391fdc06-747c-40fb-824c-4eeeb34cd40d.jpg)
![8](https://user-images.githubusercontent.com/5674572/143798591-9aea3962-42bd-4733-981e-d63e12e080d3.jpg)

**Comment by sml2h3** [comment]
需要自行训练，或者使用自定义字符集尝试
