### ISSUE TITLE
使用时控制台出现红色乱码

### ISSUE THREAD

**Issue by tonhajay** [sml2h3/ddddocr#193]
<img width="663" alt="屏幕截图 2024-05-31 234245" src="https://github.com/sml2h3/ddddocr/assets/168407108/2935bea8-8334-434f-9465-45f00d743165">
为什么我使用classification后会出现红色乱码？我试着把logging相关代码看了一下，找不到问题

**Comment by pengjinfu** [comment]
新版会出现这样的情况，暂时我也在想办法解决

**Comment by xiuzhi233** [comment]
![luanma](https://github.com/sml2h3/ddddocr/assets/95073508/84e80cf6-e301-41d2-98dc-5879e8636b2d)
我也发现了这个问题，但是不影响使用。不过还是希望解决一下，看了源码，也打了断点，没试出来是哪出现的问题。不知道是不是被识别的图片带出来的，但是感觉也不是。希望大佬有结论了回复一下

**Comment by k186** [comment]
[W:onnxruntime:, execution_frame.cc:858 VerifyOutputSizes] Expected shape from model of {1,-1} does not match actual shape of {24,1,8210} for output 387  感觉是这个错误。。我放 linux 下 就能看见这个 但是本机调试 看不见

**Comment by sml2h3** [comment]
已修复，更新1.5.4
