### ISSUE TITLE
2024-06-15 14:48:03.7487590 [W:onnxruntime:, execution_frame.cc:879 onnxruntime::ExecutionFrame::VerifyOutputSizes] Expected shape from model of {1,-1} does not match actual shape of {19,1,8210} for output 387

### ISSUE THREAD

**Issue by xk-mt** [sml2h3/ddddocr#197]
![image](https://github.com/sml2h3/ddddocr/assets/77874955/63ed1916-ec00-497f-95b5-a30b39b03056)

    新模型 = ddddocr.DdddOcr(show_ad=False)
新模型.classification(image_bytes)
然后就报这个东西，可能是什么原因导致的，需要反馈什么信息，我都方便提供

**Comment by sml2h3** [comment]
已经修复，更新1.5.4

**Comment by xk-mt** [comment]
> 已经修复，更新1.5.4



> 已经修复，更新1.5.4
好的，谢谢哥
