### ISSUE TITLE
i have got error！！！1.5.4

### ISSUE THREAD

**Issue by chengriyue** [sml2h3/ddddocr#198]
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

我的环境是python3.12.3 ，用的ddddocr 1.5.4

**Comment by chengriyue** [comment]
# example.py
import ddddocr

ocr = ddddocr.DdddOcr()
文件里面才就写了这两句

**Comment by chengriyue** [comment]
除了降级numpy包没有别的办法吗

**Comment by sml2h3** [comment]
目前看可能只能等降级，等待相关依赖更新~

**Comment by chengriyue** [comment]
降级到 numpy =  1.26.4 对您的包不会有什么影响吗,就针对于ddddocr1.5.4来说

**Comment by ArcticLampyrid** [comment]
应该需要等 onnxruntime 支持 NumPy 2.0
https://github.com/microsoft/onnxruntime/pull/21085

**Comment by sml2h3** [comment]
目前测试应该没啥问题了
