### ISSUE TITLE
最后一个字母靠近边缘时经常识别错误

### ISSUE THREAD

**Issue by wooxi** [sml2h3/ddddocr#199]
网址  https://www.goofish.pro/login
![image](https://github.com/sml2h3/ddddocr/assets/59468499/230d9e63-4536-4d77-af64-ed4e26f89197)
这种最后一个字母靠近边缘时的验证码经常识别不出来，有没有办法或自定义参数调整识别范围

因为当我把验证码截图下来，截取范围稍大，让所有字符都在图片中，没有字符靠近边缘时，就能几乎百分百能识别正确了
但这样有点麻烦，还得精确查找验证码的坐标~

**Comment by sml2h3** [comment]
这个问题是会有的，最佳处理办法是预处理一下，增加一个近似颜色的边框
