### ISSUE TITLE
使用时报错

### ISSUE THREAD

**Issue by Arabot9** [sml2h3/ddddocr#2]
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x00000219E6A236D0>

**Comment by sml2h3** [comment]
传入的是图片得bytes数据吗

**Comment by sml2h3** [comment]
> PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x00000219E6A236D0>

传入的是图片得bytes数据吗？有可能图片是损坏的

**Comment by lengyue-ck** [comment]
{
    "status": 200,
    "result": "",
    "msg": "cannot identify image file <_io.BytesIO object at 0x7fcd24bced60>"
}
