### ISSUE TITLE
安装报错？

### ISSUE THREAD

**Issue by suyin-long** [sml2h3/ddddocr#20]
使用命令 `pip install ddddocr` 安装时报错：
```
ERROR: Could not find a version that satisfies the requirement onnxruntime (from ddddocr) (from versions: none)
ERROR: No matching distribution found for onnxruntime
```
怎么回事？

Python版本：3.10.0

**Comment by suyin-long** [comment]
貌似是Python版本过高的原因，我换成Python 3.9.7安装成功了。

**Comment by suyin-long** [comment]
使用Python 3.9.7安装ddddocr后测试了下，验证码识别倒是识别出来了，但是一直报这个是什么意思？
```
2021-12-05 20:06:22.2321541 [W:onnxruntime:, execution_frame.cc:770 onnxruntime::ExecutionFrame::VerifyOutputSizes] Expected shape from model of {1,19} does not match actual shape of {1,22} for output output
```

**Comment by sml2h3** [comment]
> 使用Python 3.9.7安装ddddocr后测试了下，验证码识别倒是识别出来了，但是一直报这个是什么意思？
> 
> ```
> 2021-12-05 20:06:22.2321541 [W:onnxruntime:, execution_frame.cc:770 onnxruntime::ExecutionFrame::VerifyOutputSizes] Expected shape from model of {1,19} does not match actual shape of {1,22} for output output
> ```

不用理会，或者下1.10版本的，3.8应该可以下，那个把这个警告去掉了
