### ISSUE TITLE
大小写问题

### ISSUE THREAD

**Issue by zhangshitan** [sml2h3/ddddocr#201]
大写的英文字符，识别出来总是小写，偶尔能识别出大写。
比如这个图片，识别出来就是  dcx5
![code](https://github.com/sml2h3/ddddocr/assets/108561202/5408f922-eb9d-4491-afda-e18f7d388221)

**Comment by sml2h3** [comment]
大小写输出是完全随机的，因为最初样本问题，量级过大，无法一一清洗，所以模型对大小写的输出处于随机不可控的状态
