### ISSUE TITLE
在手机 termux安装失败

### ISSUE THREAD

**Issue by yazigegeda** [sml2h3/ddddocr#202]
我在手机上面使用termux进行安装失败了提示信息

`
done
INFO: pip is looking at multiple versions of ddddocr to determine which version is compatible with other requirements. This could take a while.
Collecting ddddocr
  Downloading ddddocr-1.5.4-py3-none-any.whl.metadata (17 kB)
  Downloading ddddocr-1.5.3-py3-none-any.whl.metadata (16 kB)
  Downloading ddddocr-1.5.2-py3-none-any.whl.metadata (16 kB)
  Downloading ddddocr-1.4.11-py3-none-any.whl.metadata (11 kB)
  Downloading ddddocr-1.4.10-py3-none-any.whl.metadata (10 kB)
  Downloading ddddocr-1.4.9-py3-none-any.whl.metadata (10 kB)
  Downloading ddddocr-1.0.6-py3-none-any.whl.metadata (1.2 kB)
INFO: pip is still looking at multiple versions of ddddocr to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install ddddocr==1.0.6, ddddocr==1.4.10, ddddocr==1.4.11, ddddocr==1.4.9, ddddocr==1.5.2, ddddocr==1.5.3, ddddocr==1.5.4 and ddddocr==1.5.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    ddddocr 1.5.5 depends on onnxruntime
    ddddocr 1.5.4 depends on onnxruntime
    ddddocr 1.5.3 depends on onnxruntime
    ddddocr 1.5.2 depends on onnxruntime
    ddddocr 1.4.11 depends on onnxruntime
    ddddocr 1.4.10 depends on onnxruntime
    ddddocr 1.4.9 depends on onnxruntime
    ddddocr 1.0.6 depends on onnxruntime

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

`

![Screenshot_2024-06-20-14-46-53-35_84d3000e3f4017145260f7618db1d683](https://github.com/sml2h3/ddddocr/assets/63853093/0e47b9bd-02cf-4b0c-9991-66ae10bcc32a)

**Comment by sml2h3** [comment]
手机一般是arm芯片，arm芯片原生onnxruntime不支持，需要自行寻找解决办法
