### ISSUE TITLE
自定义字符集问题

### ISSUE THREAD

**Issue by JetLei** [sml2h3/ddddocr#203]
如果 ocr.set_ranges(1)，但是返回的结果也不一定为纯数字吗
![1718877425195](https://github.com/sml2h3/ddddocr/assets/58629508/fef8e70d-3a52-4cdf-8de2-b80a3f7654c6)

**Comment by sml2h3** [comment]
第一，乱码已经解决了，更新最新版即可
第二，需要贴一下代码，设置范围也需要在classification函数中设置参数才会正确返回
