### ISSUE TITLE
训练图片之前，程序对图片默认做了哪些预处理？能否文档中明确一下做了哪些预处理，方便用户直接使用训练好的ONNX模型?

### ISSUE THREAD

**Issue by wxy5001** [sml2h3/ddddocr#205]
没找到源码，能否文档中注明一下，训练之前对图片做了哪些预处理，方便用户直接对ONNX模型进行使用，直接可以使用onnxruntime或者转ncnn之类的直接使用？

**Comment by sml2h3** [comment]
[dddd_trainer](https://github.com/sml2h3/dddd_trainer)
