### ISSUE TITLE
请教一下关于提高正确识别率的问题

### ISSUE THREAD

**Issue by onlyJinx** [sml2h3/ddddocr#21]
在直接识别的情况下会出现挺高的错误（见下面图片），想请教下在已知验证码图片有以下规律的情况下想提高识别率，大佬能否提供一点意见。。

1、全都是单一色调
2、全部都是五个字母组成
3、干扰因素只有一条从左到右的线条

![image](https://user-images.githubusercontent.com/21324835/144783241-3225c7e3-cb8d-4d51-866f-507df49785ac.png)

**Comment by sml2h3** [comment]
1、转灰度
2、通过膨胀减少字母中的噪音，使其变成一个实心的字体
3、通过腐蚀可以去除大部分横向线条

**Comment by onlyJinx** [comment]
好的， 谢谢建议。
有疑问再来请教~

**Comment by onlyJinx** [comment]
对了，完成以上操作有啥python库可以推荐吗？
有个关键字我好搜索学习使用。。

**Comment by sml2h3** [comment]
> 对了，完成以上操作有啥python库可以推荐吗？ 有个关键字我好搜索学习使用。。

opencv就可以
