### ISSUE TITLE
pillow 新版已棄用ANTIALIAS，請版主更新

### ISSUE THREAD

**Issue by minghuiclark** [sml2h3/ddddocr#219]
image = image.resize((int(image.size[0] * (64 / image.size[1])), 64), Image.ANTIALIAS).convert('L')
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

**Comment by CodingMoeButa** [comment]
附议。

**Comment by sml2h3** [comment]
已经在好几个版本之前就修复这个问题了，需要你删除本地老的版本，安装最新版本的ddddocr~

**Comment by iamiccam** [comment]
> 已经在好几个版本之前就修复这个问题了，需要你删除本地老的版本，安装最新版本的ddddocr~

我今天刚拉的ddddocr，还是报这个错

**Comment by CodingMoeButa** [comment]
该不会是忘记推送Pypi了吧。
