### ISSUE TITLE
请问如何根据文字描述选择图形？

### ISSUE THREAD

**Issue by Ianna-Ding** [sml2h3/ddddocr#226]
<img width="251" alt="0b38cd9f24acc37a5565bd2318486ab" src="https://github.com/user-attachments/assets/8ecda316-b3e7-4ba9-8205-e245cc01fdc1">
验证码如图，请问如何根据上方文字点选到正确的图形？

**Comment by Meliodas-gpu** [comment]
识别出位置，截取图片，训练数据判断图形，再根据长宽高，判断大小

**Comment by Ianna-Ding** [comment]
> 识别出位置，截取图片，训练数据判断图形，再根据长宽高，判断大小

还是需要自己训练啊😔谢谢您！
