### ISSUE TITLE
除了卧槽/牛逼，还想问问以后会不会支持旋转验证码

### ISSUE THREAD

**Issue by photkey** [sml2h3/ddddocr#23]
![image](https://user-images.githubusercontent.com/60434581/147858012-8fdbd51f-3c93-48d5-bfa2-62aae38838cf.png)

比方百度旋转验证码这种

**Comment by sml2h3** [comment]
可以支持

**Comment by iszmxw** [comment]
> 可以支持

现在可以了吗
