### ISSUE TITLE
看起来不支持识别大写字母

### ISSUE THREAD

**Issue by hjdhnx** [sml2h3/ddddocr#231]
我用大写字母的图片进行识别，预期是D，识别结果却是小写的d

```python
from ddddocr import DdddOcr
import unittest

ocr = DdddOcr(show_ad=False, beta=True)


class TestOcr(unittest.TestCase):
    def test_ocr_d(self):
        with open('test.png', 'rb') as f:
            ocr.set_ranges(2)
            text1 = ocr.classification(f.read())
            ret = text1[:1]
            self.assertEqual(ret, 'D')


if __name__ == '__main__':
    unittest.main()
```

测试图片如图:
![test](https://github.com/user-attachments/assets/3fd98dda-e8a9-4efb-9184-1ea79731b765)

**Comment by xia0028** [comment]
我也是，数字7识别为/

**Comment by hjdhnx** [comment]
> 我也是，数字7识别为/

我解决问题了，可以参考我这个项目 https://github.com/hjdhnx/font-decoder
使用了微信ocr拿来针对ddddocr识别出的英文字母，矫正大小写问题

**Comment by lotomer** [comment]
已经提交pull request，等待合并。如果着急，可以参考修改的部分手动修改本地对应的__init__.py文件：

**Comment by hjdhnx** [comment]
> 已经提交pull request，等待合并。如果着急，可以参考修改的部分手动修改本地对应的__init__.py文件：

大佬666，膜拜大佬

**Comment by sml2h3** [comment]
已合并代码
