### ISSUE TITLE
能选择字符集 很棒！ 顺便问问 可以设置字符数量吗？

### ISSUE THREAD

**Issue by dlliang14** [sml2h3/ddddocr#232]
如题。感觉还不是很稳啊

**Comment by nvhetd** [comment]
请问怎么选择字符集 @dlliang14

**Comment by nvhetd** [comment]
请问怎么选择字符集，谢谢 @dlliang14

**Comment by sml2h3** [comment]
> 请问怎么选择字符集，谢谢 @dlliang14

使用最新版本ddddocr即可，参考文档有写自定义字符集的
