### ISSUE TITLE
能否支持下py3.13版本

### ISSUE THREAD

**Issue by chinaxuxin** [sml2h3/ddddocr#233]

**Comment by 777miss** [comment]
我也希望能支持下python3.13

**Comment by ganhj99** [comment]
希望能支持python 3.13

**Comment by sml2h3** [comment]
可以的，今晚支持~

**Comment by nemowang2003** [comment]
`Image.ANTIALIAS`在Pillow10.0.0之后被移除了，但Pillow9.5.0不支持python3.13。#251 可以修复，希望作者可以抽空合并，感谢！
