### ISSUE TITLE
set_ranges 完還是會得到 charset 外的符號

### ISSUE THREAD

**Issue by vincent0408** [sml2h3/ddddocr#235]
設完 set_ranges = 1 後，我還是會得到大寫英文字母有時候會有數字，難道我的設定方法有錯誤嗎

```
ocr = ddddocr.DdddOcr(show_ad=False)
ocr.set_ranges(1)
```

**Comment by lotomer** [comment]
已经提交pull request，等待合并。如果着急，可以参考修改的部分手动修改本地对应的__init__.py文件

**Comment by vincent0408** [comment]
> 已经提交pull request，等待合并。如果着急，可以参考修改的部分手动修改本地对应的__init__.py文件

感謝指點，已參考
