### ISSUE TITLE
识别效果不好的图收集

### ISSUE THREAD

**Issue by sml2h3** [sml2h3/ddddocr#24]
在这里可以把你觉得识别效果不好的图片发在这里。
希望贴3张以上原图，可以包含原图链接。

**Comment by progromyang** [comment]
![Dumped](https://user-images.githubusercontent.com/54520034/148327204-4d3a90a2-18dd-4987-9dc7-3875ea0628d9.jpg)
![MEM_05D5A128_00000E80](https://user-images.githubusercontent.com/54520034/148327210-ee5b78dd-80cb-4e5c-b9f9-37cca15bbf98.jpg)
![APS7N5TXGLE`E${`P~IHPAQ](https://user-images.githubusercontent.com/54520034/148327237-4e044364-54e1-4bc2-a8dd-4667442ff1eb.jpg)

**Comment by hubaccgit** [comment]
![376_img](https://user-images.githubusercontent.com/79556183/148328842-4c049b90-447c-49dc-895f-985b7a848927.png)
![392_img](https://user-images.githubusercontent.com/79556183/148328853-f9945d5a-65bc-4f7e-b4bd-df44ebe3e4ea.png)
![415_img](https://user-images.githubusercontent.com/79556183/148328863-702afa9c-f697-4f8b-819e-ef2f876a80ca.png)
![419_img](https://user-images.githubusercontent.com/79556183/148328883-4de01c24-4e51-4f6c-8d03-9e4d37a055a5.png)
![474_img](https://user-images.githubusercontent.com/79556183/148328901-9d47ded2-ab6b-4113-b7ff-045bf7cfe68a.png)
![970_img](https://user-images.githubusercontent.com/79556183/148328922-b469dc7a-9f2c-4d1c-9321-79b20bdb031b.png)
![964_img](https://user-images.githubusercontent.com/79556183/148328938-b7eeb680-fe88-4b2f-bcaa-35db7e76d284.png)
![946_img](https://user-images.githubusercontent.com/79556183/148328944-37a873e5-4347-469f-ab6f-519396cb2bba.png)
![862_img](https://user-images.githubusercontent.com/79556183/148328967-4757610c-61f0-40e8-b909-18eda4144715.png)
![871_img](https://user-images.githubusercontent.com/79556183/148328953-bdd9e3b3-147a-4bb1-9785-aa7bed7ae37e.png)
![815_img](https://user-images.githubusercontent.com/79556183/148328960-5a172848-4d90-41a2-a257-0a45a98ce022.png)
![786_img](https://user-images.githubusercontent.com/79556183/148329035-adedaee1-90c6-43ab-a1c4-f146e58659f9.png)
![725_img](https://user-images.githubusercontent.com/79556183/148329058-f7b1c81c-1f83-40c1-a74c-23d1882956d8.png)
![751_img](https://user-images.githubusercontent.com/79556183/148329062-17f75788-b6bb-4cd0-88cb-58ef8393273d.png)
![755_img](https://user-images.githubusercontent.com/79556183/148329063-f2d57de9-6114-4278-85bf-1d29eac813d9.png)
![770_img](https://user-images.githubusercontent.com/79556183/148329064-45d1f28d-b19b-4f02-bcec-dc58fd0d8284.png)
![781_img](https://user-images.githubusercontent.com/79556183/148329065-62464f1d-c481-47b5-93b7-c3cf4827a31e.png)
![786_img](https://user-images.githubusercontent.com/79556183/148329068-c26007c8-92a3-40fc-8cbc-fa6ab4c47625.png)
![798_img](https://user-images.githubusercontent.com/79556183/148329071-a077bd73-4c85-455a-acca-2fc848f326b4.png)
![120_img ](https://user-images.githubusercontent.com/79556183/148329121-561a9b65-4802-4bff-935e-5d9011270e7d.png)
![121_img](https://user-images.githubusercontent.com/79556183/148329125-2ab05cfe-1193-4c69-a63b-7f8a38acd902.png)
![143_img](https://user-images.githubusercontent.com/79556183/148329127-6cbe189a-3105-4b33-94b3-67a2e4034860.png)
![144_img](https://user-images.githubusercontent.com/79556183/148329129-cbd70f96-7bcf-47c4-9072-b7c0f70e652a.png)
![155_img](https://user-images.githubusercontent.com/79556183/148329131-0889a069-1427-4f4a-a679-961145611f66.png)
![159_img](https://user-images.githubusercontent.com/79556183/148329133-0c16133d-c67f-4728-b81a-823bbf04d4a8.png)
![276_img](https://user-images.githubusercontent.com/79556183/148329134-736b6601-cb1e-4a74-b58e-3835e9878f1f.png)
![312_img](https://user-images.githubusercontent.com/79556183/148329135-e09a93ab-c83c-4e87-a41c-7cce016a59bd.png)
![346_img](https://user-images.githubusercontent.com/79556183/148329136-a15dc180-6494-4ec1-b50f-68a5225b4f68.png)
![361_img](https://user-images.githubusercontent.com/79556183/148329138-20d80878-daa5-4cd3-9ae3-15241f18f199.png)
![1_img](https://user-images.githubusercontent.com/79556183/148329177-ae0e3c13-5644-4f1d-a5e8-17e6a2b7f5f1.png)
![6_img](https://user-images.githubusercontent.com/79556183/148329185-8d139d23-f5a5-4b95-9fb9-5560d5c4abd8.png)
![8_img](https://user-images.githubusercontent.com/79556183/148329187-f87cb3e5-8baf-4e3b-a0f8-b9963ebe90f0.png)
![22_img](https://user-images.githubusercontent.com/79556183/148329189-a609248d-0bb7-4997-ba81-3a6095915c57.png)
![23_img](https://user-images.githubusercontent.com/79556183/148329190-d38762a8-cd23-4fd0-a0d0-ef8165d568b2.png)
![27_img](https://user-images.githubusercontent.com/79556183/148329194-577e5d0d-1ed2-4c87-a128-cbc26dccecc7.png)
![28_img](https://user-images.githubusercontent.com/79556183/148329195-313c6c30-acc9-428b-b7a3-88705cf847b7.png)
![32_img](https://user-images.githubusercontent.com/79556183/148329196-07310186-df50-40fb-a5df-a9e9460b3c93.png)
![35_img](https://user-images.githubusercontent.com/79556183/148329198-434c0467-3a3c-454c-b487-d1e7db893c1b.png)
![48_img](https://user-images.githubusercontent.com/79556183/148329199-8b88773e-3b30-4dfb-8ee8-b7db6575a56d.png)
![51_img](https://user-images.githubusercontent.com/79556183/148329200-af2ef3d3-a342-4b19-a464-2ac4a6ff5d26.png)
![55_img](https://user-images.githubusercontent.com/79556183/148329201-16943da7-6923-4038-b82b-252f8f2ed082.png)
![57_img](https://user-images.githubusercontent.com/79556183/148329203-1161a1bd-fe15-4265-9e23-d058cf83235f.png)
![58_img](https://user-images.githubusercontent.com/79556183/148329204-16a86af6-0e06-417b-89d0-17e79df1e00d.png)
![59_img](https://user-images.githubusercontent.com/79556183/148329205-03ab79c6-6745-43d1-a861-feead8f49553.png)
![60_img](https://user-images.githubusercontent.com/79556183/148329208-facea5ad-0dfd-42ea-bb7b-bc1569f7ba32.png)
![63_img](https://user-images.githubusercontent.com/79556183/148329209-d3eac18a-4254-47e7-9552-d7a1ca047303.png)
![81_img](https://user-images.githubusercontent.com/79556183/148329212-1e3682bb-b52e-4001-b04f-30e2e1ca8f71.png)
![82_img](https://user-images.githubusercontent.com/79556183/148329213-9ee58c67-bbd0-4ce2-a127-8b859f8ecc58.png)
![83_img](https://user-images.githubusercontent.com/79556183/148329215-e5a9fe80-4402-494a-a445-2672f681669a.png)

**Comment by hubaccgit** [comment]
### 下面是四位的都识别成3位或者2位了  
![553_img](https://user-images.githubusercontent.com/79556183/148329920-65f1b19a-047b-4c08-88e0-3a9254c90205.png)
![767_img](https://user-images.githubusercontent.com/79556183/148329926-c84c8b59-e3d1-45e2-9e67-d90c0d2284e6.png)
![822_img](https://user-images.githubusercontent.com/79556183/148329930-6a03b3bd-a21e-4b0d-bcc3-5c7f73ff361e.png)
![855_img](https://user-images.githubusercontent.com/79556183/148329933-16848e3f-989a-4d89-92cd-28b047b29449.png)
![879_img](https://user-images.githubusercontent.com/79556183/148329935-8047a4ab-688d-4f41-b035-663515124865.png)

**Comment by xiaozhan0806** [comment]
![b8e4a5b3-8fbd-484c-9c12-f4a7fd0e871b](https://user-images.githubusercontent.com/92793419/148333671-c332d23d-f213-4f40-88b7-913af49d20d0.jpg)
![3f944e6c-c161-455d-81e0-47356f912c44](https://user-images.githubusercontent.com/92793419/148333677-7f179917-1fd8-43b3-8fbf-c8e7fc78f22e.jpg)

**Comment by xiaozhan0806** [comment]
麻烦看看这个地址的验证码，谢谢 https://cas.jdair.net/captcha.htm?.tmp=0.6527627102557132

**Comment by xiaozhan0806** [comment]
还有这个中文的，谢谢https://www.tianjin-air.com/air/api/uc/v1/profile/profile/authenticaiton/captchas

**Comment by xiaozhan0806** [comment]
![QQ图片20220106134055](https://user-images.githubusercontent.com/92793419/148334369-2fc402e2-a141-438f-9002-1cfacfce02ef.png)

**Comment by hubaccgit** [comment]
### 跑一万次四位数的字母+数字组合的验证码，有904个位数不对  
不对的附件： [error.zip](https://github.com/sml2h3/ddddocr/files/7820018/error.zip)

**Comment by dongchengtao** [comment]
![image](https://user-images.githubusercontent.com/21034284/148353446-d2675906-2b1d-43f5-9d68-4ebfeb3db6bf.png)
![image](https://user-images.githubusercontent.com/21034284/148353477-5768d0ee-c0fa-45df-875d-b03fd42cf845.png)
![image](https://user-images.githubusercontent.com/21034284/148353507-887b85db-6cba-4109-be1a-6694bed87670.png)
这个地址
http://biguo100.com/core/Code.asp?rd=5a7TS4GzwK
感谢

**Comment by void285** [comment]
这一批目前识别的正确率应该低于10%，不知能否改善？
一共46个，已用正确的验证码命名，不过人眼识别率也不高，命名可能不正确。
[captchar-alphs.zip](https://github.com/sml2h3/ddddocr/files/7832598/captchar-alphs.zip)

预览样品：
![XQWR](https://user-images.githubusercontent.com/612912/148632556-804998fa-8314-4fa6-9ca2-f519b28fd314.png)
![CXDT](https://user-images.githubusercontent.com/612912/148632560-a6b82b60-7454-45f4-aa8f-59bf93b11ddf.png)
![WFHN](https://user-images.githubusercontent.com/612912/148632562-336db620-34fc-4ef0-a5e0-5e18684f5423.png)

**Comment by TOKIMEKl** [comment]
[img.zip](https://github.com/sml2h3/ddddocr/files/7853900/img.zip)
这批验证码成功率只有50%上下，不知道能否改善，感谢大佬

**Comment by TokimekiMemorial** [comment]
这批验证码成功率只有50%上下，不知道能否改善，感谢大佬
[img.zip](https://github.com/sml2h3/ddddocr/files/7854005/img.zip)

**Comment by jager-Man** [comment]
![1](https://user-images.githubusercontent.com/51510743/149434547-f5201ca0-630c-46ac-8efc-c1d71f6d269d.png)
识别为5位或者不准

**Comment by jager-Man** [comment]
![4](https://user-images.githubusercontent.com/51510743/149434795-10493878-728b-4fdd-8629-85082b625b42.png)
![1](https://user-images.githubusercontent.com/51510743/149434821-2a29d15d-9d1b-47f7-ac96-686171596189.png)
![2](https://user-images.githubusercontent.com/51510743/149434830-e77c70ca-837e-4aef-828a-f4164107eea5.png)
![3](https://user-images.githubusercontent.com/51510743/149434842-490c1f07-e342-4fe5-a505-a1c1e5aea66a.png)
识别位数为5位或者错误

**Comment by ewwerpm** [comment]
大佬，用ocr = ddddocr.DdddOcr(old=True) 识别率80%，用ocr = ddddocr.DdddOcr() ，识别率只有45%。如何提高识别率啊？

链接：https://pan.baidu.com/s/1kJdt6hvXciY7yJJCE78OPw 
提取码：clog

**Comment by ewwerpm** [comment]
我识别不出来的原因，大部分是被验证码前面的干扰线迷惑了。多加了个字母或数字，导致结果不对

**Comment by ewwerpm** [comment]
![图片](https://user-images.githubusercontent.com/25223652/152639669-08422304-a1ba-45a0-bd09-e3674534ebaf.png)

**Comment by Hecate2** [comment]
https://www.internationalsaimoe.com/captcha

**Comment by benson-singapore** [comment]
![vietcombank_202202251144224363924510](https://user-images.githubusercontent.com/24889151/156699370-f6467819-0fb1-4b1b-96f2-831a58133ed7.png)
![vietcombank_202202251145099399686812](https://user-images.githubusercontent.com/24889151/156699377-048ee25d-cdb7-427a-93c7-30c2214e1768.png)
![vietcombank_202202251216007130383806](https://user-images.githubusercontent.com/24889151/156699381-80af920c-416b-4489-9af6-ea7625ef2927.png)
![vietcombank_202202251216256205062854](https://user-images.githubusercontent.com/24889151/156699382-a7f29256-a2e6-4080-8776-69b38d4e556e.png)
![vietcombank_202202251217463492377106](https://user-images.githubusercontent.com/24889151/156699383-ef459b01-a3c5-4be0-92e2-0a1ac538d95a.png)
![vietcombank_202202251218097504958420](https://user-images.githubusercontent.com/24889151/156699385-2633c59c-ea2d-464f-9e89-b938df229a37.png)

**Comment by haha-chen** [comment]
![getVerify1](https://user-images.githubusercontent.com/34367539/156868586-0d03816a-4e4d-4082-a0e2-811f036cc935.jpg)
![getVerify2](https://user-images.githubusercontent.com/34367539/156868593-2217556c-7a10-4ab6-9231-270b3bdd25b3.jpg)
![getVerify3](https://user-images.githubusercontent.com/34367539/156868595-9a1a5864-6e54-4b70-a2f5-804e117432b7.jpg)
![verify_code](https://user-images.githubusercontent.com/34367539/156868597-a82b27e3-dffc-4c0d-917c-0ae5fcd991c3.jpg)
![verify_code2](https://user-images.githubusercontent.com/34367539/156868599-b19ef05a-990a-47dc-9cca-8fb8a27133d5.jpg)
谢谢大佬

**Comment by vD1S** [comment]
这种验证码百分百失败，都是返回单字母 `d`

![15-43-43](https://user-images.githubusercontent.com/26621506/161372788-c290a154-18fb-445b-8385-14cff597c70d.png)
![15-43-07](https://user-images.githubusercontent.com/26621506/161372797-2517b428-bf6c-4b71-99a1-da08c630552a.png)
![15-43-16](https://user-images.githubusercontent.com/26621506/161372798-0d869b84-c54e-419d-98ed-1f84fc3a75a8.png)
![15-43-21](https://user-images.githubusercontent.com/26621506/161372799-6c95e6f7-b907-46b9-9b70-d17a38936b3d.png)
![15-43-29](https://user-images.githubusercontent.com/26621506/161372801-8002f85a-daeb-4554-9ccb-97792d0ecaff.png)
![15-43-34](https://user-images.githubusercontent.com/26621506/161372802-1289156f-3eaa-4a01-8019-0011e593c8a6.png)
![15-43-40](https://user-images.githubusercontent.com/26621506/161372803-82519719-f47a-4477-9a2e-15f105df6403.png)
![15-44-07](https://user-images.githubusercontent.com/26621506/161372804-281a558a-325a-49cf-9ab8-fce615a0db64.png)
![15-44-13](https://user-images.githubusercontent.com/26621506/161372805-41ca15b5-dc73-40f0-95f8-52cc099fd228.png)
![15-44-18](https://user-images.githubusercontent.com/26621506/161372806-f9f9db86-1ec6-4eb7-b390-8d605ddf9d0f.png)
![15-44-25](https://user-images.githubusercontent.com/26621506/161372808-127d4b6b-8c88-4537-a8b7-2eecffb2e0f5.png)
![15-44-34](https://user-images.githubusercontent.com/26621506/161372809-2506e529-758a-434b-8744-a13f28a4bcf3.png)

**Comment by echo918** [comment]
![image](https://user-images.githubusercontent.com/55477099/162370851-ca629f24-c407-43c4-9509-ee43d06b520a.png)
![code](https://user-images.githubusercontent.com/55477099/162371011-4379787d-5706-4715-bef1-6c5944bf1aa9.png)
![code](https://user-images.githubusercontent.com/55477099/162371661-7fe4109a-1d21-4dd6-ba20-6c3f4e6b2aca.png)
感谢大佬。

**Comment by HeartBlade** [comment]
![3](https://user-images.githubusercontent.com/1889607/163909408-bd8662dd-9a98-4df1-824b-a29b07d96cf7.png)
6029识别成60Z9
PS：能否指定识别的字符内容？比如只识别数字

**Comment by HeartBlade** [comment]
![3](https://user-images.githubusercontent.com/1889607/163909408-bd8662dd-9a98-4df1-824b-a29b07d96cf7.png)
6029识别成60Z9
PS：能否指定识别的字符内容？比如只识别数字

**Comment by s348268281** [comment]
![2022-04-20](https://user-images.githubusercontent.com/43004817/164364862-35ab2499-a43e-415d-b4e5-5340c6babc22.png)
PMBR识别成pmsr
![image](https://user-images.githubusercontent.com/43004817/164364918-37aaac6a-38d4-442c-82a3-9c9ca63dfcb2.png)

**Comment by S-kewen** [comment]
https://ptlogin.4399.com/ptlogin/captcha.do?captchaId=11

希望能出一个教程，可以自己训练自己的model（针对开发者）

**Comment by petitchamp** [comment]
您好，
我遇到一个需要区分大小写的验证码，成功率不高，有时候比较明显的大小写，比如大写Q会识别成q，A识别成a

有时候还会识别出中文

![captcha1](https://user-images.githubusercontent.com/1801213/166106447-9eec5594-3d32-436f-87aa-be521cc4950d.png)
![captcha](https://user-images.githubusercontent.com/1801213/166106449-fd768f7d-0ba7-4519-aebe-af2457fffdb5.png)
![captcha3](https://user-images.githubusercontent.com/1801213/166106506-29df362b-1cb1-42c5-8efa-581557b801f1.png)
![captcha](https://user-images.githubusercontent.com/1801213/166106571-804469b4-4cb5-42ff-9955-ba982c54dc8b.png)
![cfPf5](https://user-images.githubusercontent.com/1801213/166106617-27bf0609-5992-443e-ab8b-5244ba7571c1.png)

**Comment by kerlomz** [comment]
> 您好， 我遇到一个需要区分大小写的验证码，成功率不高，有时候比较明显的大小写，比如大写Q会识别成q，A识别成a
> 
> 有时候还会识别出中文
> 
> ![captcha1](https://user-images.githubusercontent.com/1801213/166106447-9eec5594-3d32-436f-87aa-be521cc4950d.png) ![captcha](https://user-images.githubusercontent.com/1801213/166106449-fd768f7d-0ba7-4519-aebe-af2457fffdb5.png) ![captcha3](https://user-images.githubusercontent.com/1801213/166106506-29df362b-1cb1-42c5-8efa-581557b801f1.png) ![captcha](https://user-images.githubusercontent.com/1801213/166106571-804469b4-4cb5-42ff-9955-ba982c54dc8b.png) ![cfPf5](https://user-images.githubusercontent.com/1801213/166106617-27bf0609-5992-443e-ab8b-5244ba7571c1.png)

ddddocr目前的训练样本没有区分大小写，建议采集标注样本发给作者以后集成进去

**Comment by kerlomz** [comment]
> 您好， 我遇到一个需要区分大小写的验证码，成功率不高，有时候比较明显的大小写，比如大写Q会识别成q，A识别成a
> 
> 有时候还会识别出中文
> 
> ![captcha1](https://user-images.githubusercontent.com/1801213/166106447-9eec5594-3d32-436f-87aa-be521cc4950d.png) ![captcha](https://user-images.githubusercontent.com/1801213/166106449-fd768f7d-0ba7-4519-aebe-af2457fffdb5.png) ![captcha3](https://user-images.githubusercontent.com/1801213/166106506-29df362b-1cb1-42c5-8efa-581557b801f1.png) ![captcha](https://user-images.githubusercontent.com/1801213/166106571-804469b4-4cb5-42ff-9955-ba982c54dc8b.png) ![cfPf5](https://user-images.githubusercontent.com/1801213/166106617-27bf0609-5992-443e-ab8b-5244ba7571c1.png)

或者附上原图的链接，方便作者采集

**Comment by kerlomz** [comment]
> 

图片是透明的话，自己添加一个白色背景即可

**Comment by kerlomz** [comment]
> 这种验证码百分百失败，都是返回单字母 `d`
> 
> ![15-43-43](https://user-images.githubusercontent.com/26621506/161372788-c290a154-18fb-445b-8385-14cff597c70d.png) ![15-43-07](https://user-images.githubusercontent.com/26621506/161372797-2517b428-bf6c-4b71-99a1-da08c630552a.png) ![15-43-16](https://user-images.githubusercontent.com/26621506/161372798-0d869b84-c54e-419d-98ed-1f84fc3a75a8.png) ![15-43-21](https://user-images.githubusercontent.com/26621506/161372799-6c95e6f7-b907-46b9-9b70-d17a38936b3d.png) ![15-43-29](https://user-images.githubusercontent.com/26621506/161372801-8002f85a-daeb-4554-9ccb-97792d0ecaff.png) ![15-43-34](https://user-images.githubusercontent.com/26621506/161372802-1289156f-3eaa-4a01-8019-0011e593c8a6.png) ![15-43-40](https://user-images.githubusercontent.com/26621506/161372803-82519719-f47a-4477-9a2e-15f105df6403.png) ![15-44-07](https://user-images.githubusercontent.com/26621506/161372804-281a558a-325a-49cf-9ab8-fce615a0db64.png) ![15-44-13](https://user-images.githubusercontent.com/26621506/161372805-41ca15b5-dc73-40f0-95f8-52cc099fd228.png) ![15-44-18](https://user-images.githubusercontent.com/26621506/161372806-f9f9db86-1ec6-4eb7-b390-8d605ddf9d0f.png) ![15-44-25](https://user-images.githubusercontent.com/26621506/161372808-127d4b6b-8c88-4537-a8b7-2eecffb2e0f5.png) ![15-44-34](https://user-images.githubusercontent.com/26621506/161372809-2506e529-758a-434b-8744-a13f28a4bcf3.png)

图片是透明的话，自己添加一个白色背景即可

**Comment by bluesky2030** [comment]
百分之99失败，地址
https://bbs.6994.cn/misc.php?mod=seccode&update=28965&idhash=cSi9aaw6

**Comment by zys645** [comment]
https://account.hpool.in/api/user/verificationcode?session=inKmowPdCkvBsvvBCzqbJdN0WDc4GrMA
这个失败率很高

**Comment by 286844626** [comment]
可以支持识别符号么
![1](https://user-images.githubusercontent.com/34543121/172757203-03f871bd-bcc3-4262-93e9-b342eed5bbda.jpg)
![2](https://user-images.githubusercontent.com/34543121/172757207-f6a367b0-e244-4c23-adbe-47c16cdfe80d.jpg)
![0](https://user-images.githubusercontent.com/34543121/172757208-6ac668a4-6514-404d-8e3d-4972efc8e424.jpg)
，

**Comment by doyoman** [comment]
第一张图使用old模型可以识别，其余图全部识别错误；使用新模型以下图全部识别不出来
![1](https://user-images.githubusercontent.com/63859866/175449565-0cc0c921-05dc-4e9f-aae5-c7061e725488.jpg)
![2](https://user-images.githubusercontent.com/63859866/175449581-8cf31cc1-4598-4eea-a2b8-3b6b6342d575.jpg)
![3](https://user-images.githubusercontent.com/63859866/175449593-f32f9a60-8328-41a6-9d68-cf834a61dc88.jpg)
![4](https://user-images.githubusercontent.com/63859866/175449601-555fd13d-2fab-4294-9285-631c55af39b4.jpg)
![5](https://user-images.githubusercontent.com/63859866/175449612-3bb14b18-d820-4483-a6f6-ad5c87443b83.jpg)
![6](https://user-images.githubusercontent.com/63859866/175449617-75e27a37-34e3-44bb-95c2-8ed69783019f.jpg)
![7](https://user-images.githubusercontent.com/63859866/175449623-8b053816-8a85-41ca-8efa-ef3fe7d0640f.jpg)
![8](https://user-images.githubusercontent.com/63859866/175449631-ef4ce4ea-0e64-417e-b058-960eb2bc2e52.jpg)
![9](https://user-images.githubusercontent.com/63859866/175449648-ab5d36c8-a829-4668-9904-e16fe4837913.jpg)

**Comment by ewwerpm** [comment]
我用dddd识别，识别率只有80%。 用我自己的模型，识别率达到99.6%。 如果大家   有兴趣，可以把图片发给我，我帮你们训练识别。1437399109@qq.com

**Comment by ewwerpm** [comment]
> 第一张图使用old模型可以识别，其余图全部识别错误；使用新模型以下图全部识别不出来 ![1](https://user-images.githubusercontent.com/63859866/175449565-0cc0c921-05dc-4e9f-aae5-c7061e725488.jpg) ![2](https://user-images.githubusercontent.com/63859866/175449581-8cf31cc1-4598-4eea-a2b8-3b6b6342d575.jpg) ![3](https://user-images.githubusercontent.com/63859866/175449593-f32f9a60-8328-41a6-9d68-cf834a61dc88.jpg) ![4](https://user-images.githubusercontent.com/63859866/175449601-555fd13d-2fab-4294-9285-631c55af39b4.jpg) ![5](https://user-images.githubusercontent.com/63859866/175449612-3bb14b18-d820-4483-a6f6-ad5c87443b83.jpg) ![6](https://user-images.githubusercontent.com/63859866/175449617-75e27a37-34e3-44bb-95c2-8ed69783019f.jpg) ![7](https://user-images.githubusercontent.com/63859866/175449623-8b053816-8a85-41ca-8efa-ef3fe7d0640f.jpg) ![8](https://user-images.githubusercontent.com/63859866/175449631-ef4ce4ea-0e64-417e-b058-960eb2bc2e52.jpg) ![9](https://user-images.githubusercontent.com/63859866/175449648-ab5d36c8-a829-4668-9904-e16fe4837913.jpg)

我用dddd识别，识别率只有80%。 用我自己的模型，识别率达到99.6%。 如果大家 有兴趣，可以把图片发给我，我帮你们训练识别。[1437399109@qq.com](mailto:1437399109@qq.com)

**Comment by Dragon-qing** [comment]
![agzc](https://user-images.githubusercontent.com/86229701/184532728-2d5867ed-c50c-4c1b-8bba-08b140d96e4d.jpg)
![dhdx](https://user-images.githubusercontent.com/86229701/184532737-0541731a-e336-43f9-bf39-9f6a14a38461.jpg)
![cyph](https://user-images.githubusercontent.com/86229701/184532744-1d8edfae-b4c5-4570-b08e-bb45b7b8836e.jpg)
![rxyc](https://user-images.githubusercontent.com/86229701/184532751-e3c61a21-7f3f-4235-89b9-1c4bd3a82d99.jpg)
![xxec](https://user-images.githubusercontent.com/86229701/184532754-ce82c9ff-83f1-4f02-a514-e634c73fddcc.jpg)

**Comment by RyanLoil** [comment]
<img width="80" alt="1" src="https://user-images.githubusercontent.com/50242494/186182805-a3d39ed6-0293-4d66-b23c-ac1696b592a5.png">
<img width="80" alt="2" src="https://user-images.githubusercontent.com/50242494/186182814-4e2d1d37-6afe-477e-8d84-340c1d318b93.png">
<img width="80" alt="3" src="https://user-images.githubusercontent.com/50242494/186182818-a0e4995f-2457-4ff1-a900-7a54ec3f8cab.png">
<img width="80" alt="4" src="https://user-images.githubusercontent.com/50242494/186182823-18cc9283-256b-4b1a-b4b9-315eaf935fdd.png">
<img width="80" alt="5" src="https://user-images.githubusercontent.com/50242494/186182824-b701c2fc-98bf-40bb-af1f-bf3a57552d45.png">
<img width="80" alt="6" src="https://user-images.githubusercontent.com/50242494/186182828-72bd5e92-76ba-4561-af5f-a060c0b86381.png">

**Comment by sml2h3** [comment]
> 麻烦看看这个地址的验证码，谢谢 https://cas.jdair.net/captcha.htm?.tmp=0.6527627102557132

这个没法打开

**Comment by mddon2010** [comment]
![1](https://github.com/sml2h3/ddddocr/assets/87014053/721396d5-5e16-49db-b83b-5951b71cad02)
![3](https://github.com/sml2h3/ddddocr/assets/87014053/51fdf3bf-b659-4656-a5dc-a56f3ec5a946)
![2](https://github.com/sml2h3/ddddocr/assets/87014053/bcb612a7-a26a-4ea3-83f4-6c5414241004)

https://macaoapply.singlewindow.gd.cn/#/user/userLogin

不能準確地分析大小寫

**Comment by lsylsy2** [comment]
![1696834806 3301](https://github.com/sml2h3/ddddocr/assets/870873/8afd9671-f07c-416c-8661-9394bcf775d6)
![1696834810 2289](https://github.com/sml2h3/ddddocr/assets/870873/b54b893c-6bd6-4ed5-a14c-8495a6046007)
![1696834981 0421](https://github.com/sml2h3/ddddocr/assets/870873/7cdde8b4-1f85-4e4b-a518-c148cc716d41)
![1696904886 1619](https://github.com/sml2h3/ddddocr/assets/870873/dae54655-9bf1-451c-a257-1ac2dda97b98)
![1696916390 842](https://github.com/sml2h3/ddddocr/assets/870873/6a9fdc74-d056-4cef-af8c-031dae184573)
![1696904893 4168](https://github.com/sml2h3/ddddocr/assets/870873/d086ca57-de4f-432d-a106-0dfac3ba6def)
对有1/7/4的验证码准确度都偏低

**Comment by inertance** [comment]
from io import BytesIO
import ddddocr
import requests
from PIL import Image

CAPTCHA_URL = "https://m.ghzq.com.cn/pro/ImageServlet?key="

s = requests.session()
s.headers = {
    "Accept": "application/json, text/plain, */*",
    "Accept-Encoding": "gzip, deflate, br",
    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
    "Connection": "keep-alive",
    "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
    "Host": "m.ghzq.com.cn",
    "Origin": "https://jy.ghzq.com.cn",
    "Referer": "https://jy.ghzq.com.cn/",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
}

vcode = s.post("https://m.ghzq.com.cn/pro/ESBServlet?command=tradeapi.getcodekey").json()
key = vcode["key"]
captcha_url = CAPTCHA_URL + key
captcha_bytes = s.get(captcha_url).content
captcha_img = Image.open(BytesIO(captcha_bytes))
captcha_img.show()

orc = ddddocr.DdddOcr(beta=True)
captcha_num = orc.classification(captcha_img)
print(captcha_num) 识别不出运算符号

**Comment by Ronghefeng** [comment]
![055](https://github.com/sml2h3/ddddocr/assets/42339196/d118dd41-3142-4c41-aa7a-5bce7ca9ea2a)
![083](https://github.com/sml2h3/ddddocr/assets/42339196/f3ca0d2f-47f7-44af-af08-6e2026ed270c)
![098](https://github.com/sml2h3/ddddocr/assets/42339196/9971006b-8987-4e20-80df-429642b0db4e)
这类图片，因为存在中文，或者运算符导致无法正确识别，识别率几乎为0
