### ISSUE TITLE
简单大小写+数字场景下，识别率低

### ISSUE THREAD

**Issue by Easy-Ez** [sml2h3/ddddocr#244]
大佬，类似下面两种验证码，期望识别大小写的场景下 `ocr.set_ranges(6)`，使用 beta =False or True ，识别率都很低。

帮忙看看需要调整什么参数么。

![demo](https://github.com/user-attachments/assets/0cb60a7d-775b-4f7c-9423-d388908b8506)
![demo2](https://github.com/user-attachments/assets/cfd68208-07d6-431a-b2e0-904b44f7b3a3)

```python
ocr = ddddocr.DdddOcr(beta=True)
ocr.set_ranges(6)
image = open(path, "rb").read()
result = ocr.classification(image)
```
识别结果
0C5o
debd

**Comment by Easy-Ez** [comment]
https://github.com/sml2h3/dddd_trainer
自己训练了下， 这种简单的验证码还是轻松秒杀~

**Comment by masterAllen** [comment]
请问这种需要多少数据集啊

**Comment by Dainsleif233** [comment]
> https://github.com/sml2h3/dddd_trainer 自己训练了下， 这种简单的验证码还是轻松秒杀~

问问用了多少数据集
