### ISSUE TITLE
DdddOcr Node JS 版本

### ISSUE THREAD

**Issue by rhy3h** [sml2h3/ddddocr#245]
由於我最近在寫 Python 專案
剛好有用到這個套件
那我剛好對於 JavaScript 算熟悉
因此我就花了點時間實現

## 功能
 - [基礎 OCR 識別能力](https://github.com/rhy3h/ddddocr-node?tab=readme-ov-file#basic-ocr-recognition-capability)
 - [OCR 概率輸出](https://github.com/rhy3h/ddddocr-node?tab=readme-ov-file#ocr-probability-output)
 - [物件檢測能力](https://github.com/rhy3h/ddddocr-node?tab=readme-ov-file#object-detection-capability)

## 相關連結
[Github](https://github.com/rhy3h/ddddocr-node)
[NPM](https://www.npmjs.com/package/ddddocr-node)

想詢問若能加入此專案的 README 那就太感謝了

**Comment by sml2h3** [comment]
感谢~已加
