### ISSUE TITLE
大佬. 这张图转成base64 ocr返回是空的  det可以监测到位置,  能否det加上是哪个文字呢

### ISSUE THREAD

**Issue by xiaojia21190** [sml2h3/ddddocr#32]
![c1cc5042fe584250761b9e181f1c0674175e76d8642b553f5e6de2366d70d930QzpcVXNlcnNcQWRtaW5pc3RyYXRvclxBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcMzg0ODk1MjE1X3YyXEltYWdlRmlsZXNcMTY0MjU1OTU4NDc5M18yNkE5M0M2MS1FOTQ4LTRhNjEtOTE0MC0xNzYzQ0YzQjFEQTUucG5n](https://user-images.githubusercontent.com/16084693/150057824-1103fa43-ee95-4a3d-83ea-3025e5e96d6d.png)

**Comment by sml2h3** [comment]
可以识别
`import ddddocr


ocr = ddddocr.DdddOcr(det=True)

with open("150057824-1103fa43-ee95-4a3d-83ea-3025e5e96d6d (1).png", 'rb') as f:
    image = f.read()


res = ocr.detection(image)
print(res)`
