### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by androidcn** [sml2h3/ddddocr#35]
`pip3 install ddddocr
Collecting ddddocr
  Using cached ddddocr-1.0.6-py3-none-any.whl (6.9 MB)
Collecting Pillow
  Using cached Pillow-9.0.1-cp310-cp310-macosx_10_10_universal2.whl (3.3 MB)
ERROR: Could not find a version that satisfies the requirement onnxruntime (from ddddocr) (from versions: none)
ERROR: No matching distribution found for onnxruntime`

Python 3.10.2

不是M1 
macOS BigSur 11.6.3 (20G415)
MacBook Pro (Retina, 13-inch, Late 2013) Intel
也不支持？

**Comment by sml2h3** [comment]
> 

python版本太高，最高3.9注意看文档

**Comment by androidcn** [comment]
> > 
> 
> python版本太高，最高3.9注意看文档

Thanks！看错了，感谢，安装成功
