### ISSUE TITLE
我有一个闪动的gif验证码，4个字符，可以识别出后3个，第1个被忽略了。

### ISSUE THREAD

**Issue by ageback** [sml2h3/ddddocr#36]
提供三个样本：

![3](https://user-images.githubusercontent.com/1097481/154879966-73b6a9aa-2a3b-4b2b-9d98-82adcc7e644c.gif)
![2](https://user-images.githubusercontent.com/1097481/154880004-8952f412-3e6d-4b76-8c1e-b720f144fed1.gif)
![4](https://user-images.githubusercontent.com/1097481/154880494-ce41bd1c-067a-4f84-9540-f4f42f2ae747.gif)

代码：
`import ddddocr

ocr = ddddocr.DdddOcr(old=True)
with open('3.gif', 'rb') as f:
    img_bytes = f.read()
res = ocr.classification(img_bytes)

print(res)`

**Comment by Xbai-hang** [comment]
这种应该是它在任意一帧的时候只显示了三个字母，所以只能识别三个，个人想法是可以把 gif 逐帧抽取出来然后进行识别匹配，最后拼串

**Comment by ageback** [comment]
你说的对，是这个情况。看来要写个方法拆图片，然后逐个识别了。
