### ISSUE TITLE
MacOS无法安装

### ISSUE THREAD

**Issue by Damon-Shen** [sml2h3/ddddocr#4]
系统版本：11.4 (20F71)
设备版本：MacBook Air (M1, 2020)
pip安装提示没有版本可用
ERROR: Cannot install ddddocr==1.0.4, ddddocr==1.0.5 and ddddocr==1.0.6 because these package versions have conflicting dependencies.

**Comment by sml2h3** [comment]
因为onnxruntime的缘故，似乎无法安装在macos上，实在不好意思

> 系统版本：11.4 (20F71)
> 设备版本：MacBook Air (M1, 2020)
> pip安装提示没有版本可用
> ERROR: Cannot install ddddocr==1.0.4, ddddocr==1.0.5 and ddddocr==1.0.6 because these package versions have conflicting dependencies.
