### ISSUE TITLE
图片的base64字符串需要取头部吗

### ISSUE THREAD

**Issue by Ssummer520** [sml2h3/ddddocr#41]
传入的base64字符串有什么规则要求吗

**Comment by Ssummer520** [comment]
页面直接取到的图片base64字符串  报错binascii.Error: Incorrect padding

**Comment by Ssummer520** [comment]
图片的base64字符串需要加密传吗

**Comment by pesh178** [comment]
需要把base64转成png在传

**Comment by sml2h3** [comment]
保留/9j/开头的部分，之前的部分都不要
