### ISSUE TITLE
询问下大概什么时候能支持macos m系列处理器?或者有没有自己编译onnxruntime的文档?谢谢

### ISSUE THREAD

**Issue by jiayouzl** [sml2h3/ddddocr#46]
感谢!~

**Comment by sml2h3** [comment]
> 感谢!~

https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-MacOSX-arm64.sh
使用这个安装m1的conda环境，在这个支持m1的conda里面创建的python环境可以解决不能在m1使用ddddocr的问题
