### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)

### ISSUE THREAD

**Issue by merlin02306** [sml2h3/ddddocr#47]
pip无法安装ddddocr，换了好几个源，都提示这个
ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
ERROR: No matching distribution found for onnxruntime

**Comment by jingjianqian** [comment]
+1

**Comment by 001SM** [comment]
+1

**Comment by pikpiksec** [comment]
Python3.10不支持，可以改为3.9

**Comment by towelong** [comment]
3.9貌似也不行，我这边报错，我是3.9.9

**Comment by towelong** [comment]
3.9貌似也不行，我这边报错，我是3.9.9

**Comment by xhpk** [comment]
3.9.7失败

**Comment by sml2h3** [comment]
目前onnxruntime不支持相对高版本的python（近一两年python的更新频率太快了），建议安装3.8-3.9
