### ISSUE TITLE
这种验证码百分百失败

### ISSUE THREAD

**Issue by vD1S** [sml2h3/ddddocr#48]
这种验证码百分百失败，都是返回单字母 `d`

![15-43-43](https://user-images.githubusercontent.com/26621506/161372788-c290a154-18fb-445b-8385-14cff597c70d.png)
![15-43-07](https://user-images.githubusercontent.com/26621506/161372797-2517b428-bf6c-4b71-99a1-da08c630552a.png)
![15-43-16](https://user-images.githubusercontent.com/26621506/161372798-0d869b84-c54e-419d-98ed-1f84fc3a75a8.png)
![15-43-21](https://user-images.githubusercontent.com/26621506/161372799-6c95e6f7-b907-46b9-9b70-d17a38936b3d.png)
![15-43-29](https://user-images.githubusercontent.com/26621506/161372801-8002f85a-daeb-4554-9ccb-97792d0ecaff.png)
![15-43-34](https://user-images.githubusercontent.com/26621506/161372802-1289156f-3eaa-4a01-8019-0011e593c8a6.png)
![15-43-40](https://user-images.githubusercontent.com/26621506/161372803-82519719-f47a-4477-9a2e-15f105df6403.png)
![15-44-07](https://user-images.githubusercontent.com/26621506/161372804-281a558a-325a-49cf-9ab8-fce615a0db64.png)
![15-44-13](https://user-images.githubusercontent.com/26621506/161372805-41ca15b5-dc73-40f0-95f8-52cc099fd228.png)
![15-44-18](https://user-images.githubusercontent.com/26621506/161372806-f9f9db86-1ec6-4eb7-b390-8d605ddf9d0f.png)
![15-44-25](https://user-images.githubusercontent.com/26621506/161372808-127d4b6b-8c88-4537-a8b7-2eecffb2e0f5.png)
![15-44-34](https://user-images.githubusercontent.com/26621506/161372809-2506e529-758a-434b-8744-a13f28a4bcf3.png)

**Comment by sml2h3** [comment]
不好意思才回复，这种是png的，调用如下代码可以看到
![image](https://user-images.githubusercontent.com/17084976/166340216-b65935a0-36c3-4471-b2f6-593dcc4e958c.png)
![image](https://user-images.githubusercontent.com/17084976/166340248-043bc0af-8d3c-4831-aa57-65b762879d2a.png)
整个图片都是纯黑色的RGBA，利用的alpha的透明度去做的显示，这种需要自己去转换成RGB模式的图片
