### ISSUE TITLE
File "D:\codetools\anaconda3\lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>     from .onnxruntime_pybind11_state import *  # noqa ImportError: DLL load failed while importing onnxruntime_pybind11_state: 找不到指定的模块。

### ISSUE THREAD

**Issue by YuchaoLau** [sml2h3/ddddocr#52]
import ddddocr 跳这个错误怎么解决

**Comment by YuchaoLau** [comment]
pip install onnxruntime==1.2.0

**Comment by xiaohuanxiongi** [comment]
```
Traceback (most recent call last):
  File "/usr/local/var/functions/ap-guangzhou/lam-nr3yic7g/flask_demo-1650266770/src/app.py", line 4, in <module>
    import ddddocr
  File "/usr/local/var/functions/ap-guangzhou/lam-nr3yic7g/flask_demo-1650266770/src/ddddocr/__init__.py", line 8, in <module>
    import onnxruntime
  File "/usr/local/var/functions/ap-guangzhou/lam-nr3yic7g/flask_demo-1650266770/src/onnxruntime/__init__.py", line 35, in <module>
    raise import_capi_exception
  File "/usr/local/var/functions/ap-guangzhou/lam-nr3yic7g/flask_demo-1650266770/src/onnxruntime/__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, set_seed, \
  File "/usr/local/var/functions/ap-guangzhou/lam-nr3yic7g/flask_demo-1650266770/src/onnxruntime/capi/_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
ModuleNotFoundError: No module named 'onnxruntime.capi.onnxruntime_pybind11_state'
```
这腾讯云部署报这个错怎么解决呢?我看了`onnxruntime`版本是1.11.0了,Python是3.6版本的

**Comment by YuchaoLau** [comment]
大概率是onnxruntime版本问题，我用的是1.8.0，你可以试一下这个版本

**Comment by YuchaoLau** [comment]
> ```
> Traceback (most recent call last):
>   File "/usr/local/var/functions/ap-guangzhou/lam-nr3yic7g/flask_demo-1650266770/src/app.py", line 4, in <module>
>     import ddddocr
>   File "/usr/local/var/functions/ap-guangzhou/lam-nr3yic7g/flask_demo-1650266770/src/ddddocr/__init__.py", line 8, in <module>
>     import onnxruntime
>   File "/usr/local/var/functions/ap-guangzhou/lam-nr3yic7g/flask_demo-1650266770/src/onnxruntime/__init__.py", line 35, in <module>
>     raise import_capi_exception
>   File "/usr/local/var/functions/ap-guangzhou/lam-nr3yic7g/flask_demo-1650266770/src/onnxruntime/__init__.py", line 23, in <module>
>     from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, set_seed, \
>   File "/usr/local/var/functions/ap-guangzhou/lam-nr3yic7g/flask_demo-1650266770/src/onnxruntime/capi/_pybind_state.py", line 32, in <module>
>     from .onnxruntime_pybind11_state import *  # noqa
> ModuleNotFoundError: No module named 'onnxruntime.capi.onnxruntime_pybind11_state'
> ```
> 
> 这腾讯云部署报这个错怎么解决呢?我看了`onnxruntime`版本是1.11.0了,Python是3.6版本的

大概率是onnxruntime版本问题，我用的是1.8.0，你可以试一下这个版本

**Comment by YuchaoLau** [comment]
> ```
> Traceback (most recent call last):
>   File "/usr/local/var/functions/ap-guangzhou/lam-nr3yic7g/flask_demo-1650266770/src/app.py", line 4, in <module>
>     import ddddocr
>   File "/usr/local/var/functions/ap-guangzhou/lam-nr3yic7g/flask_demo-1650266770/src/ddddocr/__init__.py", line 8, in <module>
>     import onnxruntime
>   File "/usr/local/var/functions/ap-guangzhou/lam-nr3yic7g/flask_demo-1650266770/src/onnxruntime/__init__.py", line 35, in <module>
>     raise import_capi_exception
>   File "/usr/local/var/functions/ap-guangzhou/lam-nr3yic7g/flask_demo-1650266770/src/onnxruntime/__init__.py", line 23, in <module>
>     from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, set_seed, \
>   File "/usr/local/var/functions/ap-guangzhou/lam-nr3yic7g/flask_demo-1650266770/src/onnxruntime/capi/_pybind_state.py", line 32, in <module>
>     from .onnxruntime_pybind11_state import *  # noqa
> ModuleNotFoundError: No module named 'onnxruntime.capi.onnxruntime_pybind11_state'
> ```
> 
> 这腾讯云部署报这个错怎么解决呢?我看了`onnxruntime`版本是1.11.0了,Python是3.6版本的

onnxruntime我用的是1.8.0，你可以试一下这个版本

**Comment by xiaohuanxiongi** [comment]
还是一样的报错，切换版本到1.8.0了；但是我更换了Python版本3.7可以了。。

**Comment by YuchaoLau** [comment]
> 还是一样的报错，切换版本到1.8.0了；但是我更换了Python版本3.7可以了。。

OK

**Comment by sml2h3** [comment]
统一说一下解决办法，遇到这个情况的话说明你的pip版本低了，使用命令
`python -m pip install --upgrade pip`
升级一下pip即可，再重新安装ddddocr即可
`pip uninstall ddddocr`
`pip install ddddocr`
