### ISSUE TITLE
如何禁止控制台输出“欢迎使用ddddocr，本项目专注带动行业内卷，个人博客:wenanzhe.com”

### ISSUE THREAD

**Issue by kevinfszu** [sml2h3/ddddocr#56]
存在问题：目前需要在 node.js 中调用 ddddocr，python 是通过 print(data) 的方式返回数据给 node.js 的，而 ddddocr 默认输出的“欢迎使用ddddocr，本项目专注带动行业内卷，个人博客:wenanzhe.com”会污染 python 返回的结果。

期望效果：应该有一种配置方式可以禁止输出 ddddocr 库默认 print 的内容。

![微信截图_20220424175849](https://user-images.githubusercontent.com/5536550/164971087-865dc057-a1eb-4c4b-930f-a347cbba6127.png)

**Comment by sml2h3** [comment]
初始化的时候传参show_ad=False

**Comment by bukaixyz** [comment]
直接把这行代码删掉不就行了🌝
