### ISSUE TITLE
我的问题

### ISSUE THREAD

**Issue by Issacty** [sml2h3/ddddocr#59]
我看show的data是可以用点选文字的部分可以使用单应性矩阵做辅助匹配，那如果是多重单应性矩阵搞出来的文字要咋办

**Comment by sml2h3** [comment]
> 我看show的data是可以用点选文字的部分可以使用单应性矩阵做辅助匹配，那如果是多重单应性矩阵搞出来的文字要咋办

不是非常明白您的意思，可以举图例说明一下嘛
