### ISSUE TITLE
解析每次都弹警告信息

### ISSUE THREAD

**Issue by arvinyi** [sml2h3/ddddocr#7]
2021-07-30 15:45:48.3226553 [W:onnxruntime:, execution_frame.cc:721 onnxruntime::ExecutionFrame::VerifyOutputSizes] Expected shape from model of {1,19} does not match actual shape of {1,20} for output output
![screenImg03](https://user-images.githubusercontent.com/88183795/127619825-37944811-3e40-4122-be1d-05562552a0d6.png)

**Comment by sml2h3** [comment]
假装看不到吧，这个我也不知道该咋解决了。。

> 2021-07-30 15:45:48.3226553 [W:onnxruntime:, execution_frame.cc:721 onnxruntime::ExecutionFrame::VerifyOutputSizes] Expected shape from model of {1,19} does not match actual shape of {1,20} for output output
> ![screenImg03](https://user-images.githubusercontent.com/88183795/127619825-37944811-3e40-4122-be1d-05562552a0d6.png)

**Comment by vuesets** [comment]
你可以设置 

```python
onnxruntime.set_default_logger_severity(3)
```

[来源链接](https://github.com/neuralchen/SimSwap/issues/65)

**Comment by instant-high** [comment]
Insert this code into _./insightface_func/face_detect_crop_single.py_ and  _./insightface_func/face_detect_crop_multi.py_
to supress error msg:

10 import onnxruntime
11 onnxruntime.set_default_logger_severity(3)

This will show if onnx running on CPU or GPU:
12 print( "Running on: " + onnxruntime.get_device()  )
optional:
#13 input("Press Enter to continue...")

**Comment by wsgehaishan520** [comment]
https://blog.csdn.net/weixin_38443388/article/details/108677003

**Comment by sml2h3** [comment]
pip安装1.0.9版即可
