### ISSUE TITLE
licenses inconsistency

### ISSUE THREAD

**Issue by SoftwareEthicsResearcher** [sml2h3/ddddocr#76]
Hello, I am doing research in software engineering ethics. I found different licenses in repo. May I know which license repo follows? I would like to highlight this as a transparency concern.
•  Repo License: Apache license 2.0, 
o  Different license : MIT in setup.py.
 
Regards, Software Ethics Researcher.

**Comment by sml2h3** [comment]
> Hello, I am doing research in software engineering ethics. I found different licenses in repo. May I know which license repo follows? I would like to highlight this as a transparency concern. • Repo License: Apache license 2.0, o Different license : MIT in setup.py.
> 
> Regards, Software Ethics Researcher.

In accordance with MIT license
