### ISSUE TITLE
请问何时支持Python 3.10版本 windows 64bit

### ISSUE THREAD

**Issue by blueicesir** [sml2h3/ddddocr#77]
Using cached ddddocr-1.0.6-py3-none-any.whl (6.9 MB)
Requirement already satisfied: numpy in d:\python310\lib\site-packages (from ddddocr) (1.22.4)
Requirement already satisfied: Pillow in d:\python310\lib\site-packages (from ddddocr) (9.1.1)
ERROR: Ignored the following versions that require a different python version: 1.0.8 Requires-Python <3.8; 1.1.0 Requires-Python <3.9; 1.2.0 Requires-Python <3.10; 1.3.0 Requires-Python <3.10; 1.3.1 Requires-Python <3.10; 1.4.0 Requires-Python <3.10; 1.4.1 Requires-Python <3.10; 1.4.2 Requires-Python <3.10; 1.4.3 Requires-Python <3.10
ERROR: Could not find a version that satisfies the requirement onnxruntime (from ddddocr) (from versions: none)
ERROR: No matching distribution found for onnxruntime

python --version
Python 3.10.4

**Comment by sml2h3** [comment]
另外也可以参考https://github.com/microsoft/onnxruntime/issues/11117使用dev版本onnxruntime，并从ddddocr源代码中构建使用ddddocr相关功能
