### ISSUE TITLE
Fatal error: DynamicQuantizeLSTM is not a registered function/op

### ISSUE THREAD

**Issue by Mr-Harry** [sml2h3/ddddocr#8]
Fatal error: DynamicQuantizeLSTM is not a registered function/op

**Comment by sml2h3** [comment]
> Fatal error: DynamicQuantizeLSTM is not a registered function/op

应该是由于python版本低，安装了低版本的onnxruntime导致的，python<3.8可以安装1.0.8版本，
pip install ddddocr==1.0.8
