### ISSUE TITLE
感谢sml2h3 升级，现在ddddocr支持python3.10了

### ISSUE THREAD

**Issue by zhonghai9967** [sml2h3/ddddocr#83]
在python3.10中安装，试用，非常好用。
有几个“友商”作品，如cnocr、pyocr、pytesseract、easyocr、PaddleOCR，只有pytesseract安装成功，但识别率太低了，结果中还有 "\r\x0a"等特殊字符。
再次感谢sml2h3，不用专门为ddddocr安装3.9了

**Comment by sml2h3** [comment]
r\x0 是啥，可以贴图看看吗

**Comment by Epiphany7725** [comment]
应该还不支持吧，我今天下了为什么报错呢
