### ISSUE TITLE
detect返回结果中，增加检测出的文本信息

### ISSUE THREAD

**Issue by aih8** [sml2h3/ddddocr#88]
如题，detect模式，除了坐标信息外，返回识别出的文字信息

**Comment by aih8** [comment]
当前的返回结果如下
`
{
    "status": 200,
    "result": [
        [
            162,
            36,
            182,
            56
        ],
        [
            123,
            86,
            144,
            106
        ],
        [
            59,
            89,
            81,
            111
        ],
        [
            162,
            111,
            182,
            129
        ],
        [
            20,
            5,
            38,
            23
        ],
        [
            71,
            6,
            89,
            24
        ],
        [
            53,
            6,
            71,
            23
        ],
        [
            3,
            6,
            21,
            23
        ],
        [
            87,
            5,
            107,
            24
        ]
    ],
    "msg": ""
}
`

**Comment by aih8** [comment]
待识别的图片，如下：
![Snipaste_2022-08-16_14-09-26](https://user-images.githubusercontent.com/18440794/184811657-91525b97-7ec1-416b-afac-6e353cec919d.png)

**Comment by yuyuypjk** [comment]
同样需要识别这种验证码

**Comment by sml2h3** [comment]
你可以选择自己根据bbox信息进行切割识别，毕竟通用目标检测识别的不仅仅只有文字，还可能碰到图标的位置检测
