### ISSUE TITLE
help!!!import ddddocr时，报错ImportError: DLL load failed while importing onnxruntime_pybind11_state: 找不到指定的模块。

### ISSUE THREAD

**Issue by zyf1118** [sml2h3/ddddocr#90]
报错ImportError: DLL load failed while importing onnxruntime_pybind11_state: 找不到指定的模块

请问如何解决

**Comment by zyf1118** [comment]
加了作者微信未通过，无法加群求救，希望有大佬能帮我解决安装环境问题，折腾了2天都没装好，好多问题

**Comment by sml2h3** [comment]
一般是缺少微软运行库环境，推荐使用：https://www.ghxi.com/yxkhj.html/comment-page-1?replytocom=13935   下载并安装
安装完以后再安装ddddocr就可以了

**Comment by sml2h3** [comment]
如果没什么问题了的话我这边就先关闭了哈

> 加了作者微信未通过，无法加群求救，希望有大佬能帮我解决安装环境问题，折腾了2天都没装好，好多问题

**Comment by betterzhou-github** [comment]
> 一般是缺少微软运行库环境，推荐使用：https://www.ghxi.com/yxkhj.html/comment-page-1?replytocom=13935 下载并安装 安装完以后再安装ddddocr就可以了

有版本要求不？安装最新的就可以了吧？

**Comment by sml2h3** [comment]
> > 一般是缺少微软运行库环境，推荐使用：https://www.ghxi.com/yxkhj.html/comment-page-1?replytocom=13935 下载并安装 安装完以后再安装ddddocr就可以了
> 
> 有版本要求不？安装最新的就可以了吧？

对的，另外你加上我微信了嘛
