### ISSUE TITLE
ddddocr.DdddOcr(ocr=True)在centos系统报Segmentation fault (core dumped)错误

### ISSUE THREAD

**Issue by 18463105800** [sml2h3/ddddocr#96]
在centos系统中尝试安装了python3.8版本和3.9版本，只要是运行ddddocr.DdddOcr(ocr=True)代码就会报coredump错误（ocr为false不会），看了下报错行数是在”self.__ort_session = onnxruntime.InferenceSession(self.__graph_path, providers=self.__providers)“代码中，怀疑和onnxruntime有关，尝试安装了多个版本都不行(后面测试1.6.0一个比较老的版本没问题），onnxruntime升级到最新版后虽然没有cordump，但就是一直卡着不出结果。辛苦大佬们帮忙看看这个问题，看看是否遇到了类似的

**Comment by zytomorrow** [comment]
和你出现了类似的问题，但是比你复杂点

我打包了一个docker镜像，基础环境是3.9.10，在LXC ubuntu 22.04 LTS上卡着不出结果，但是同一个镜像在VPS  ubuntu 22.04就正常

**Comment by zytomorrow** [comment]
> 和你出现了类似的问题，但是比你复杂点
> 
> 我打包了一个docker镜像，基础环境是3.9.10，在LXC ubuntu 22.04 LTS上卡着不出结果，但是同一个镜像在VPS ubuntu 22.04就正常

基础镜像切换到python:3.8.13-slim，onnxruntime指定1.6.0，运行正常

**Comment by 18463105800** [comment]
> onnxruntime指定1.6.0
